dist: xenial
language: python
addons:
  artifacts: true
python:
- '3.8'
- '3.7'
stages:
  - Black
  - Pylint
  - Deploy
before_install:
  - sudo apt-get install -y --no-install-recommends bc
addons:
  apt:
    update: true
install: &requirements
- pip install -r requirements.txt
- pip install tox-travis
- pip install -e .
script: tox
after_success: codecov
jobs:
  include:
  - stage: Black
    install: *requirements
    script:
    - echo excluding $(git config --file .gitmodules --get-regexp path | awk '{ print
      $2 }')
    - black --exclude $(git config --file .gitmodules --get-regexp path | awk '{ print
      $2 }') --check .
  - stage: Pylint
    install: *requirements
    script:
    - pip --no-cache-dir install pylint-runner
    - pylint_runner --rcfile=.pylintrc --output-format=text . | tee pylint.txt
    - score=$(sed -n 's/^Your code has been rated at \([-0-9.]*\)\/.*/\1/p' pylint.txt)
    - if (( $(echo "$score < 8" |bc -l) )); then echo "Your Pylint score is too low, $score < 8!"; exit 1; fi
  - stage: Deploy
    script: skip
    deploy:
      provider: pypi
      user: __token__
      password:
        secure: "rhY5kcsS/cLBkmlS9nIuuE9GAholHbZ1NYjVt3+1b/rZ6BhGk/S71RaX9OIOpQeSnr/4UWBEiMu6gbHlUtQv0iiGGj8aOZ1LbW5CT2ljNFy0/hsbmN4n10nXm2bebnFZTkxCeErJHzNZxznf3NsRseQcT6b8aOwVnTTJAQ+9gx0FjeGEuVjr4ZBCHjelJtoA9qdQEv/9IbbfelAzWWaYCqXSc/DbsHhvTvqQ1d8sAyYrdKvUiPTTc+bz/6IV53oml2vC2EFGf3RQdnwldEyVJGgGl0gJ2PBoVgfnJ9L6clIqYPmvVyAfQKYiT966EG7IQsO4NtzhtR1hoT/NkgQJVIqFcHivU+sN0dar0vObmDYEBhQ74Iq9GwK0Cp/0n3FpnxhSF0paq6OEt7cAV5bVVQYgw/JMLuccj8eLRbFMXFUOMcZRFAILeKQvT3QGG9FQ/OwdqnEXWMzxMgey9lcj6+RAn/G3XTeUeU08jCtT48DU5CkmaSgIdkTLoEoRL1Jdrlq36H8yFA4sVeJ9pdHDcgoyTKn8HGv830tpTAl6auVTNjZOdRlaX7QLMjS5OMWvz2Sj7Gu5gnGfqiNHrb3EwhGdu4dEgDJmkLlAH6pH1vL+x2kQgrqggxu1FEWjaioFk2GHHB7n2uL4arh1lCraQcNk5bBEhZV0e327BCkzqyg="
      on:
        tags: true
        all_branches: true
    # Deploy only if tag respects semantic versioning pre-pended with v (e.g. v0.1.0)
    if: tag =~ /^v(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(-(0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(\.(0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*)?(\+[0-9a-zA-Z-]+(\.[0-9a-zA-Z-]+)*)?$/
